### ISSUE TITLE
Pocr_CFL can not terminate

### ISSUE THREAD

**Issue by enochii** [kisslune/POCR#1]
Dear author, thanks for the good work!

When I run `cfl.cpp` with `StdCFL` in a small test(`art.peg`), it quickly returns the result: 

![image](https://user-images.githubusercontent.com/33364190/202905803-adb466b1-6a26-45a2-8488-31c12e68a8d5.png)

But running with `Pocr_CFL`, the program does not terminate(at least tens of seconds). By the way, in my case, the `-pocr` or `-std` seems not work, so I change the code manually to make it use `Pocr_CFL`.

![image](https://user-images.githubusercontent.com/33364190/202906053-94c6c9e1-8f9a-4df3-b0ff-aa8468284817.png)

**Comment by kisslune** [comment]
Hi, @enochii. Thank you for your attention. We have noticed this issue and are trying to improve the structure of POCR. Anyway, you can change the code however you like to suit your needs. Hope this tool will help you.

**Comment by enochii** [comment]
Got it, thanks a lot!
