### ISSUE TITLE
graph files of cpu2017

### ISSUE THREAD

**Issue by qingkaishi** [kisslune/POCR#5]
Hi, it's a nice OOPSLA paper and I enjoy reading it. I wonder if you can provide the graph files of the programs mentioned in the OOPSLA paper. I understand that cpu2017 itself is not open source, so I just wonder if the graph files are available. Many thanks.

**Comment by kisslune** [comment]
Hello. @qingkaishi. Thank you for your attention. You can find the CPU2017 graphs from https://github.com/kisslune/CPU17-graphs. For the consideration of confidentiality, we hide some details in the graph. But you can still get results very close to what we presented in the paper using the current version of POCR.

**Comment by qingkaishi** [comment]
That’s very nice. Thanks.
