### ISSUE TITLE
Issue about Preprocessing for Alias Analysis

### ISSUE THREAD

**Issue by enochii** [kisslune/POCR#6]
Thanks for the excellent code and good work~ I have a question about the preprocessing for the alias analysis.

Given the below input graph for *Alias Analysis*, the results of `StdAA` and `PocrAA` is inconsistent, where `StdAA` gives `#SumEdges` as 17 and `PocrAA` gives 11. When turning off the preprocessing, the results are consistent.

```shell
0	2	d
0	1	a
1	3	d
``` 
The preprocessed graph are given below, in which 0 and 1 are folded as 0. I guess the reason of inconsistency is, `PocrAA` use `map<ID, ID>` to store `d` since `d` is unique. But when the graph is folded(e.g., node 0 and 1), if the corresponding `d` edges(d<0, 2> <1,3>) are not folded, this assumption about "d is unique" no longer holds, so some edges may be overried. 
In the other hand, `StdAA` use `CFLData`, which uses `map<ID, NodeBS>` to store d edges, so the behavior looks different from `PocrAA`.
If the d edges are not folded, I am not sure whether some reachability pairs may be lost. For example, since d<0,2> is overrided by d<0,3>, some edges rooted from 2 is not reachable from 0 via d<0,2>?
```
0	2	d
0	3	d
```
So I guess a possible solution would be folding the d edges as well? I notice in `PEG::mergeNodeToRep()`, the logic for folding "d edges" are provided but commented. I am curious that Is there any other consideration?

Also, if I want to reproduce the results of your OOPSLA paper, which version of graph should I use here(https://github.com/kisslune/CPU17-graphs)?
- `aa-origin` with the preprocessing turned on
- `aa-simplified` with the preprocessing turned off

**Comment by kisslune** [comment]
Hi @enochii,

Thank you for finding this bug! It was fixed in the newest version.

**Comment by enochii** [comment]
Hi @kisslune ,

Many thanks for your code and contribution, learning a lot~
